### ISSUE TITLE
ГӘС (GPE)

### ISSUE THREAD

**Issue by beyimjan** [IS2AI/KazNERD#2]
> GPE - ГӘС - Географиялық әкімшілік бірліктерінің атаулары.

Географиялық әкімшілік бірліктер - ГӘБ болмай ма?

**Comment by yeshpanovrustem** [comment]
Сәлеметсіз бе. Нұсқаулықтың 12-ші бетінде берілген мәннің толық атауы беріледі: Географиялық/Әлеуметтік/Саяси мән (ГӘС).

**Comment by beyimjan** [comment]
Рахмет!

**Comment by beyimjan** [comment]
Онда сайтта https://issai.nu.edu.kz/kk/kaznerd-kaz/ қате ақпарат берілген шығар?

**Comment by yeshpanovrustem** [comment]
Аталған сайтта атаулы мәндердің тізімі мен **қысқаша** анықтамасы берілген. Толық ақпаратты нұсқаулықтан алсаңыз болады.
<img width="1158" alt="Screen Shot 2023-06-15 at 18 22 56" src="https://github.com/IS2AI/KazNERD/assets/6375187/077ea17e-1d50-4441-b367-de1fd4c7788b">
